name: 'wheres_carmen_dbt'
version: '1.0.0'
config-version: 2

profile: 'wheres_carmen_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  wheres_carmen_dbt:
    +materialized: view
    staging:
      +schema: staging
    intermediate:
      +schema: intermediate
    processed:
      +schema: processed
      +materialized: table
    analytics:
      +schema: analytics
      +materialized: view
