wheres_carmen_dbt:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: './target/wheres_carmen_dbt.duckdb'
    
    # lab:
    #   type: duckdb
    #   schema: lab
    
    # prod:
    #   type: duckdb
    #   schema: prod