wheres_carmen_dbt:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: './target/wheres_carmen_dbt_dev.duckdb'
    
    lab:
      type: duckdb
      path: './target/wheres_carmen_dbt_lab.duckdb'
    
    prod:
      type: duckdb